cd D:/Vagrant/azubu_auth

CONFIG_FILE=D:/Vagrant/azubu_auth/config/config.json
PARAMS_FILE=D:/Vagrant/azubu_auth/config/parameters.json

CFG_PORT_OR_SOCKET=8080
CFG_GRANTS_SOCKET_FILE=660
CFG_HOST=localhost
CFG_MONGO_HOST=localhost
CFG_MONGO_PORT=27017
CFG_MONGO_USER=
CFG_MONGO_PASS=
CFG_MONGO_REPLICA_DB='[]'
CFG_MONGO_DB=azubu
CFG_MONGO_SERVER_AUTO_RECONNECT=true
CFG_MONGO_SERVER_POOL_SIZE=5
CFG_MONGO_SERVER_KEEP_ALIVE=1
CFG_MONGO_REPLICA_AUTO_RECONNECT=false
CFG_MONGO_REPLICA_POOL_SIZE=10
CFG_MONGO_REPLICA_KEEP_ALIVE=1
CFG_MONGO_REPLICA_CONNECT_TIMEOUT=30000
CFG_PG_HOST=127.0.0.1
CFG_PG_DB=postgres
CFG_PG_PORT=5432
CFG_PG_USERNAME=postgres
CFG_PG_PASSWORD=


PARAMS_CFG_OAUTH2_ALLOWED_GRAND_TYPE_PASSWORD=password
PARAMS_CFG_OAUTH2_ALLOWED_GRAND_TYPE_REFRESH_TOKEN=refresh_token
PARAMS_CFG_OAUTH2_ALLOWED_GRAND_TYPE_CLIENT_CREDENTIALS=client_credentials
PARAMS_CFG_OAUTH2_ALLOWED_GRAND_TYPE_PREMIUM_BROADCASTER=http://localhost.com/login/premium-broadcaster
PARAMS_CFG_OAUTH2_ALLOWED_GRAND_TYPE_ADMIN=http://localhost.com/login/admin
PARAMS_CFG_OAUTH2_ALLOWED_GRAND_TYPE_SOCIAL=http://localhost.com
PARAMS_CFG_OAUTH2_ALLOWED_GRAND_TYPE_USER_ID=http://localhost.com/userId
PARAMS_CFG_SOCIAL_SERVICES_AVAILABLE=facebook
PARAMS_CFG_SOCIAL_SERVICES_CONFIGURATION_FACEBOOK_APPID=243243115835911
PARAMS_CFG_SOCIAL_SERVICES_CONFIGURATION_FACEBOOK_SECRET=34d578598aedacf88d6e8a9e81c28e0c
PARAMS_CFG_SOCIAL_SERVICES_CONFIGURATION_FACEBOOK_OAUTH=https://www.facebook.com/dialog/oauth
PARAMS_CFG_SOCIAL_SERVICES_CONFIGURATION_FACEBOOK_GRAPH=https://graph.facebook.com

PARAMS_CFG_MEDIA_SERVICE_IMAGE_WEB_PATH='/images/'
PARAMS_CFG_MEDIA_SERVICE_IMAGE_DEFAULT_PATH=default
PARAMS_CFG_MEDIA_SERVICE_IMAGE_DEFAULT_IMAGE_PROFILE_PHOTO_SMALL='profile-photo-small.jpg'
PARAMS_CFG_MEDIA_SERVICE_IMAGE_DIR_USER_PROFILE=userprofile
PARAMS_CFG_MEDIA_SERVICE_MEDIA_DOMAIN=http://azubulocal.com
PARAMS_CFG_AUTH_COOKIE_DOMAIN=azubulocal.com
PARAMS_CFG_AUTH_HASH_KEY=jHtmYju5GGGBdAHz
PARAMS_CFG_COOKIE_PRIVATE_DATA_NAME=Datass
PARAMS_CFG_COOKIE_PRIVATE_DATA_EXPIRE=2505600




# update config
sed -i "s|VAR_PORT_OR_SOCKET|${CFG_PORT_OR_SOCKET}|g" ${CONFIG_FILE}
sed -i "s|VAR_GRANTS_SOCKET_FILE|${CFG_GRANTS_SOCKET_FILE}|g" ${CONFIG_FILE}
sed -i "s|VAR_HOST|${CFG_HOST}|g" ${CONFIG_FILE}
sed -i "s|VAR_MONGO_HOST|${CFG_MONGO_HOST}|g" ${CONFIG_FILE}
sed -i "s|VAR_MONGO_PORT|${CFG_MONGO_PORT}|g" ${CONFIG_FILE}
sed -i "s|VAR_MONGO_USER|${CFG_MONGO_USER}|g" ${CONFIG_FILE}
sed -i "s|VAR_MONGO_PASS|${CFG_MONGO_PASS}|g" ${CONFIG_FILE}
sed -i "s|VAR_MONGO_REPLICA_DB|${CFG_MONGO_REPLICA_DB}|g" ${CONFIG_FILE}
sed -i "s|VAR_MONGO_DB|${CFG_MONGO_DB}|g" ${CONFIG_FILE}
sed -i "s|VAR_MONGO_SERVER_AUTO_RECONNECT|${CFG_MONGO_SERVER_AUTO_RECONNECT}|g" ${CONFIG_FILE}
sed -i "s|VAR_MONGO_SERVER_POOL_SIZE|${CFG_MONGO_SERVER_POOL_SIZE}|g" ${CONFIG_FILE}
sed -i "s|VAR_MONGO_SERVER_KEEP_ALIVE|${CFG_MONGO_SERVER_KEEP_ALIVE}|g" ${CONFIG_FILE}
sed -i "s|VAR_MONGO_REPLICA_AUTO_RECONNECT|${CFG_MONGO_REPLICA_AUTO_RECONNECT}|g" ${CONFIG_FILE}
sed -i "s|VAR_MONGO_REPLICA_POOL_SIZE|${CFG_MONGO_REPLICA_POOL_SIZE}|g" ${CONFIG_FILE}
sed -i "s|VAR_MONGO_REPLICA_KEEP_ALIVE|${CFG_MONGO_REPLICA_KEEP_ALIVE}|g" ${CONFIG_FILE}
sed -i "s|VAR_MONGO_REPLICA_CONNECT_TIMEOUT|${CFG_MONGO_REPLICA_CONNECT_TIMEOUT}|g" ${CONFIG_FILE}
sed -i "s|VAR_PG_HOST|${CFG_PG_HOST}|g" ${CONFIG_FILE}
sed -i "s|VAR_PG_DB|${CFG_PG_DB}|g" ${CONFIG_FILE}
sed -i "s|VAR_PG_PORT|${CFG_PG_PORT}|g" ${CONFIG_FILE}
sed -i "s|VAR_PG_USERNAME|${CFG_PG_USERNAME}|g" ${CONFIG_FILE}
sed -i "s|VAR_PG_PASSWORD|${CFG_PG_PASSWORD}|g" ${CONFIG_FILE}

cat ${CONFIG_FILE}

# update parameters config. 
sed -i "s|PARAMS_CFG_OAUTH2_ALLOWED_GRAND_TYPE_PASSWORD|${PARAMS_CFG_OAUTH2_ALLOWED_GRAND_TYPE_PASSWORD}|g" ${PARAMS_FILE}
sed -i "s|PARAMS_CFG_OAUTH2_ALLOWED_GRAND_TYPE_REFRESH_TOKEN|${PARAMS_CFG_OAUTH2_ALLOWED_GRAND_TYPE_REFRESH_TOKEN}|g" ${PARAMS_FILE}
sed -i "s|PARAMS_CFG_OAUTH2_ALLOWED_GRAND_TYPE_CLIENT_CREDENTIALS|${PARAMS_CFG_OAUTH2_ALLOWED_GRAND_TYPE_CLIENT_CREDENTIALS}|g" ${PARAMS_FILE}
sed -i "s|PARAMS_CFG_OAUTH2_ALLOWED_GRAND_TYPE_PREMIUM_BROADCASTER|${PARAMS_CFG_OAUTH2_ALLOWED_GRAND_TYPE_PREMIUM_BROADCASTER}|g" ${PARAMS_FILE}
sed -i "s|PARAMS_CFG_OAUTH2_ALLOWED_GRAND_TYPE_ADMIN|${PARAMS_CFG_OAUTH2_ALLOWED_GRAND_TYPE_ADMIN}|g" ${PARAMS_FILE}
sed -i "s|PARAMS_CFG_OAUTH2_ALLOWED_GRAND_TYPE_SOCIAL|${PARAMS_CFG_OAUTH2_ALLOWED_GRAND_TYPE_SOCIAL}|g" ${PARAMS_FILE}
sed -i "s|PARAMS_CFG_OAUTH2_ALLOWED_GRAND_TYPE_USER_ID|${PARAMS_CFG_OAUTH2_ALLOWED_GRAND_TYPE_USER_ID}|g" ${PARAMS_FILE}
sed -i "s|PARAMS_CFG_SOCIAL_SERVICES_AVAILABLE|${PARAMS_CFG_SOCIAL_SERVICES_AVAILABLE}|g" ${PARAMS_FILE}
sed -i "s|PARAMS_CFG_SOCIAL_SERVICES_CONFIGURATION_FACEBOOK_APPID|${PARAMS_CFG_SOCIAL_SERVICES_CONFIGURATION_FACEBOOK_APPID}|g" ${PARAMS_FILE}
sed -i "s|PARAMS_CFG_SOCIAL_SERVICES_CONFIGURATION_FACEBOOK_SECRET|${PARAMS_CFG_SOCIAL_SERVICES_CONFIGURATION_FACEBOOK_SECRET}|g" ${PARAMS_FILE}
sed -i "s|PARAMS_CFG_SOCIAL_SERVICES_CONFIGURATION_FACEBOOK_OAUTH|${PARAMS_CFG_SOCIAL_SERVICES_CONFIGURATION_FACEBOOK_OAUTH}|g" ${PARAMS_FILE}
sed -i "s|PARAMS_CFG_SOCIAL_SERVICES_CONFIGURATION_FACEBOOK_GRAPH|${PARAMS_CFG_SOCIAL_SERVICES_CONFIGURATION_FACEBOOK_GRAPH}|g" ${PARAMS_FILE}

sed -i "s|PARAMS_CFG_MEDIA_SERVICE_IMAGE_WEB_PATH|${PARAMS_CFG_MEDIA_SERVICE_IMAGE_WEB_PATH}|g" ${PARAMS_FILE}
sed -i "s|PARAMS_CFG_MEDIA_SERVICE_IMAGE_DEFAULT_PATH|${PARAMS_CFG_MEDIA_SERVICE_IMAGE_DEFAULT_PATH}|g" ${PARAMS_FILE}
sed -i "s|PARAMS_CFG_MEDIA_SERVICE_IMAGE_DEFAULT_IMAGE_PROFILE_PHOTO_SMALL|${PARAMS_CFG_MEDIA_SERVICE_IMAGE_DEFAULT_IMAGE_PROFILE_PHOTO_SMALL}|g" ${PARAMS_FILE}
sed -i "s|PARAMS_CFG_MEDIA_SERVICE_IMAGE_DIR_USER_PROFILE|${PARAMS_CFG_MEDIA_SERVICE_IMAGE_DIR_USER_PROFILE}|g" ${PARAMS_FILE}
sed -i "s|PARAMS_CFG_MEDIA_SERVICE_MEDIA_DOMAIN|${PARAMS_CFG_MEDIA_SERVICE_MEDIA_DOMAIN}|g" ${PARAMS_FILE}
sed -i "s|PARAMS_CFG_AUTH_COOKIE_DOMAIN|${PARAMS_CFG_AUTH_COOKIE_DOMAIN}|g" ${PARAMS_FILE}
sed -i "s|PARAMS_CFG_AUTH_HASH_KEY|${PARAMS_CFG_AUTH_HASH_KEY}|g" ${PARAMS_FILE}
sed -i "s|PARAMS_CFG_COOKIE_PRIVATE_DATA_NAME|${PARAMS_CFG_COOKIE_PRIVATE_DATA_NAME}|g" ${PARAMS_FILE}
sed -i "s|PARAMS_CFG_COOKIE_PRIVATE_DATA_EXPIRE|${PARAMS_CFG_COOKIE_PRIVATE_DATA_EXPIRE}|g" ${PARAMS_FILE}

cat ${PARAMS_FILE}